### PR TITLE
Small changes to the QS

### PR DESCRIPTION
**Pull request by Andrew-Pohl**
• Auto install some depends without asking for user input
• Echo warning if no validator name is set

### CODE REVIEW

**Comment by Andrew-Pohl** [comment]
(@leonprou can't add reviewers anymore so thought I'd tag you :)) Just some small changes I noticed when spinning up a node on a fresh install

**Comment by Andrew-Pohl** [comment]
Also fixed a bug in the system requirements (RAM & HDD) checks.

**Review by leonprou — APPROVED** [review]

**Comment by leonprou** [comment]
@Andrew-Pohl sorry for late approving this, some new conflicts now

**Comment by Andrew-Pohl** [comment]
> @Andrew-Pohl sorry for late approving this, some new conflicts now

resolved :)

**Pull request merged**
