### PR TITLE
Update bootnodes for legacy nodes running QS script

### PR DESCRIPTION
**Pull request by gr8h**

### CODE REVIEW

**Review by AliakseiMalyshau — CHANGES_REQUESTED** [review]
There are the next changes need to add:

- https://docs.nethermind.io/fundamentals/configuration#network-bootnodes - configure bootnodes;
- https://docs.nethermind.io/fundamentals/configuration#network-staticpeers - configure static peers (same as bootnodes);
- https://docs.nethermind.io/fundamentals/configuration#network-onlystaticpeers - just use static peer list instead of chainspec node list.

I don't see `--Discovery.Bootnodes` flag in the Nethermind configuration.

**Comment by gr8h** [comment]
> There are the next changes need to add:
> 
> * https://docs.nethermind.io/fundamentals/configuration#network-bootnodes - configure bootnodes;
> * https://docs.nethermind.io/fundamentals/configuration#network-staticpeers - configure static peers (same as bootnodes);
> * https://docs.nethermind.io/fundamentals/configuration#network-onlystaticpeers - just use static peer list instead of chainspec node list.
> 
> I don't see `--Discovery.Bootnodes` flag in the Nethermind configuration.

**RE Network.Bootnodes vs Discovery.Bootnodes**; It's not in the docs, but as per my testing it's the one that worked, please check this here https://github.com/NethermindEth/nethermind/issues/5334

**RE Static nodes vs Bootnodes;** based on the definition below i think we need to set the Bootnodes
- Bootnodes: for initial peer discovery
- Staticpeers: a list the client will always maintain a persistent connection with

**Comment by AliakseiMalyshau** [comment]
@gr8h thanks for the explanation because this info is absent in the docs. If so, why we need `--Network.Bootnodes` if in PR `--Discovery.Bootnodes` is working as expected?

**Review by AliakseiMalyshau — APPROVED** [review]

**Comment by gr8h** [comment]
> @gr8h thanks for the explanation because this info is absent in the docs. If so, why we need `--Network.Bootnodes` if in PR `--Discovery.Bootnodes` is working as expected?

For backward compatibility

**Pull request merged**
