### PR TITLE
Fix purge command in quickstart.sh on Debian

### PR DESCRIPTION
**Pull request by JanOwiesniak**
Guess this should be `apt-get purge ntp`

```
Usage: apt-get [options] command
       apt-get [options] install|remove pkg1 [pkg2 ...]
       apt-get [options] source pkg1 [pkg2 ...]

apt-get is a command line interface for retrieval of packages
and information about them from authenticated sources and
for installation, upgrade and removal of packages together
with their dependencies.

Most used commands:
  update - Retrieve new lists of packages
  upgrade - Perform an upgrade
  install - Install new packages (pkg is libc6 not libc6.deb)
  reinstall - Reinstall packages (pkg is libc6 not libc6.deb)
  remove - Remove packages
  purge - Remove packages and config files
  autoremove - Remove automatically all unused packages
  dist-upgrade - Distribution upgrade, see apt-get(8)
  dselect-upgrade - Follow dselect selections
  build-dep - Configure build-dependencies for source packages
  clean - Erase downloaded archive files
  autoclean - Erase old downloaded archive files
  check - Verify that there are no broken dependencies
  source - Download source archives
  download - Download the binary package into the current directory
  changelog - Download and display the changelog for the given package
```

### CODE REVIEW

**Comment by Andrew-Pohl** [comment]
Thanks for the spot @JanOwiesniak should be install :) will fix this

**Comment by leonprou** [comment]
Hello @JanOwiesniak 
Sorry the PR slipped through the cracks. Looks good
@Andrew-Pohl so can we merge this?

**Comment by Andrew-Pohl** [comment]
> Thanks for the spot @JanOwiesniak should be install not purge here :) will fix this

Actually no I'm wrong here for Debian I used timesyncd so needed to purge ntp to avoid conflicts :) so this looks good to me!.

**Review by Andrew-Pohl — COMMENTED** [review]
LGTM! :) Thanks for spotting

**Pull request merged**
